# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# ------------------------------------------------------------

name: dapr-release-notes

on:
  repository_dispatch:
    types: release_notes
jobs:
  build:
    name: Generate release notes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install PyGithub
      - name: Generate release notes
        env:
          GITHUB_TOKEN: ${{ secrets.DAPR_BOT_TOKEN }}
        run: python ./.github/scripts/generate_release_notes.py
      - name: Commit and push to repository
        env:
          GITHUB_TOKEN: ${{ secrets.DAPR_BOT_TOKEN }}
          COMMIT_MSG: |
            Generating Dapr release notes.
            skip-checks: true
        run: |
          git config user.email "Dapr Bot"
          git config user.name "daprweb@microsoft.com"
          # Update origin with token
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          # Checkout the branch so we can push back to it
          git checkout master
          git add .
          # Only commit and push if we have changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin master)